New products page components (#61)
* fix: Monorepo issues with workspaces, exports & peerDependencies

* Remove unused import in MagicUiSaasTemplate & fix import in PricingCta

* Add smart link component for avoid error TS2322 with Next Link component

* Add SocialProofBanner component

* refactor: change SmartLink export to default and update import in SocialProofBanner

* feat: add Hero and HeroMedia components with video support and thumbnails

- Added util for find the higlight text for the hero title
- Added utils for get embed & thumbnail from a youtube video url

* feat: add exports for components in package.json from ui package

* fix: add export from HeroVideoDialog component from ui package

* feat: integrate Hero component with updated props and media handling

* fix: enhance breadcrumb navigation layout and styling from products slug page